import type { Note, Requirement } from '../domain';

/**
 * Builds the instruction Motion gives the model when drafting coursework.
 *
 * Kept pure and separate from the model wrapper so the thing most worth
 * testing — what Motion actually asks for, and how untrusted material is
 * handled — can be asserted without a model.
 */

export type DraftKind = 'outline' | 'full-draft' | 'section' | 'discussion-reply' | 'revision';

export interface ComposeInput {
  kind: DraftKind;
  /** The assignment or prompt title, for orientation. */
  title: string;
  requirements: Requirement[];
  /** Source-linked notes the student captured. */
  notes: Note[];
  /** The student's existing text, when revising rather than starting. */
  existingDraft?: string;
  /** What the student asked for in their own words, when they said anything. */
  studentDirection?: string;
  targetWords?: number;
}

export interface ComposedPrompt {
  instruction: string;
  context: { label: string; text: string }[];
  targetWords: number | undefined;
}

const KIND_INSTRUCTION: Record<DraftKind, string> = {
  outline:
    'Write a working outline for this assignment: the sections the student should write, and one line on what belongs in each. Do not write the prose itself.',
  'full-draft':
    'Write a complete first draft of this assignment for the student to read, check and rewrite in their own voice. Cover every requirement listed.',
  section:
    'Write the single section named in the direction below. Leave the rest of the assignment alone.',
  'discussion-reply':
    'Write a draft reply to this discussion prompt for the student to edit before they post it.',
  revision:
    'Revise the student’s existing draft below. Keep their argument, structure and voice; improve clarity and fix anything that does not meet a requirement. Do not replace their ideas with your own.',
};

/**
 * A standing instruction attached to every draft.
 *
 * The honesty rules are here rather than in the UI because they must survive
 * whatever the caller asks for: a draft that fabricates a citation is worse
 * than no draft, and a student who cannot see which parts are unsupported
 * cannot fix them.
 */
const ALWAYS = [
  'Mark anything you could not support from the provided material with [needs a source].',
  'Never invent a citation, quotation, statistic, or reference.',
  'Where a requirement cannot be met from the material given, say so in a short note at the end rather than writing around it.',
].join(' ');

export function composeDraftPrompt(input: ComposeInput): ComposedPrompt {
  const context: { label: string; text: string }[] = [];

  if (input.requirements.length > 0) {
    context.push({
      label: 'assignment requirements',
      text: input.requirements.map((requirement, index) => `${index + 1}. ${requirement.text}`).join('\n'),
    });
  }

  for (const note of input.notes) {
    // Only material the student captured or wrote is offered as source. A block
    // previously generated by a model is excluded: feeding generated text back
    // in as if it were a source is how a draft ends up confidently wrong.
    const usable = note.blocks.filter((block) => block.origin !== 'generated');
    if (usable.length === 0) continue;
    context.push({
      label: note.title,
      text: usable.map((block) => block.text).join('\n\n'),
    });
  }

  if (input.existingDraft) {
    context.push({ label: 'the student’s current draft', text: input.existingDraft });
  }

  const instruction = [
    `Assignment: ${input.title}`,
    '',
    KIND_INSTRUCTION[input.kind],
    input.studentDirection ? `\nThe student asks: ${input.studentDirection}` : '',
    '',
    ALWAYS,
  ]
    .filter((line) => line !== '')
    .join('\n');

  return { instruction, context, targetWords: input.targetWords };
}

/**
 * Every generated artifact carries this. Not a UI nicety: the note model stores
 * `origin: 'generated'` alongside it, so the labelling survives export, copy,
 * and any future surface that renders the text.
 */
export const GENERATED_LABEL =
  'Drafted by Motion from your requirements and notes. Read it, check anything marked [needs a source], and rewrite it in your own words before you submit.';

/**
 * Fences untrusted text so a page cannot smuggle an instruction into the
 * prompt. Delimiters appearing in the text itself are neutralised, because a
 * closing tag inside quoted content would otherwise end the fence early and
 * let the remainder be read as instruction.
 *
 * Lives in core, not in the model wrapper: it is pure string handling and the
 * defence is the part most worth testing without a model present.
 */
export function fenceContext(blocks: { label: string; text: string }[]): string {
  return blocks
    .map((block) => {
      const safeLabel = block.label.replace(/[<>"]/g, '');
      const safeText = block.text.replace(/<\/?context[^>]*>/gi, '[removed]');
      return `<context source="${safeLabel}">\n${safeText}\n</context>`;
    })
    .join('\n\n');
}

/** Assembles the final prompt: fenced data first, Motion's instruction last. */
export function buildPrompt(request: {
  instruction: string;
  context: { label: string; text: string }[];
  targetWords?: number | undefined;
}): string {
  const parts = [fenceContext(request.context), '', request.instruction];
  if (request.targetWords) parts.push('', `Aim for roughly ${request.targetWords} words.`);
  return parts.filter(Boolean).join('\n');
}

/** Requirements the draft could not evidence, for the review checklist. */
export function unsupportedClaims(draft: string): string[] {
  const matches = draft.match(/[^.!?\n]*\[needs a source\][^.!?\n]*/gi) ?? [];
  return matches.map((sentence) => sentence.replace(/\s+/g, ' ').trim()).filter(Boolean);
}
