import { describe, expect, it } from 'vitest';
import { parseWorkerResult } from './responses';

const checklist = {
  id: 'checklist-1',
  courseId: 'course-1',
  taskId: null,
  title: 'Synthetic checklist',
  items: [],
  createdAt: '2026-09-11T12:00:00.000Z',
  updatedAt: '2026-09-11T12:00:00.000Z',
};

const review = {
  stats: { words: 3, sentences: 1, paragraphs: 1 },
  findings: [{
    requirementId: 'requirement-1',
    requirement: 'Explain the result.',
    coverage: 'addressed',
    evidence: 'The result is explained.',
    explanation: 'Your draft covers most of the terms this asks for.',
  }],
  constraintChecks: [{ label: 'At least 3 words', satisfied: true, detail: 'Your draft has 3 words.' }],
};

const validResults = {
  'model-status': { availability: 'available', explanation: 'Ready.' },
  'build-checklist': { checklistId: '123e4567-e89b-12d3-a456-426614174000', items: 2 },
  'get-checklist': checklist,
  'compose-draft': {
    noteId: '123e4567-e89b-12d3-a456-426614174001',
    draft: 'A synthetic draft.',
    label: 'Generated by Motion.',
    unsupported: [],
  },
  'review-draft': { review, summary: 'The draft covers the requirement.' },
  'prepare-workspace': { workflowId: 'workflow-1', reused: true },
  'ask-about-page': { answer: 'A synthetic answer.', label: 'From this page.' },
  'toggle-requirement': { updated: true },
} as const;

describe('worker result validation', () => {
  for (const [commandType, result] of Object.entries(validResults)) {
    it(`${commandType} accepts a valid result unchanged`, () => {
      expect(parseWorkerResult(commandType as keyof typeof validResults, result)).toEqual(result);
    });
  }

  it('rejects malformed model status results', () => {
    expect(parseWorkerResult('model-status', { availability: 'broken', explanation: 'No.' })).toBeNull();
    expect(parseWorkerResult('model-status', { availability: 'available', explanation: 'x'.repeat(1_001) })).toBeNull();
  });

  it('rejects malformed checklist results', () => {
    expect(parseWorkerResult('build-checklist', { checklistId: 4, items: 2 })).toBeNull();
    expect(parseWorkerResult('get-checklist', { ...checklist, title: 4 })).toBeNull();
  });

  it('rejects malformed generated draft results', () => {
    expect(parseWorkerResult('compose-draft', { ...validResults['compose-draft'], draft: 4 })).toBeNull();
    expect(parseWorkerResult('compose-draft', { ...validResults['compose-draft'], reason: 'x'.repeat(1_001) })).toBeNull();
  });

  it('rejects malformed review, workspace, chat, and toggle results', () => {
    expect(parseWorkerResult('review-draft', { review, summary: 4 })).toBeNull();
    expect(parseWorkerResult('prepare-workspace', { workflowId: null, reason: 'x'.repeat(1_001) })).toBeNull();
    expect(parseWorkerResult('ask-about-page', { answer: 'x'.repeat(20_001) })).toBeNull();
    expect(parseWorkerResult('toggle-requirement', { updated: 'yes' })).toBeNull();
  });

  it('returns null for commands without a rendered result schema', () => {
    expect(parseWorkerResult('close-workspace', { closed: 1, ungrouped: 0 })).toBeNull();
  });
});
