import { describe, expect, it } from 'vitest';
import { parseWorkerResult } from './responses';

const checklist = {
  id: 'checklist-1',
  courseId: 'course-1',
  taskId: null,
  title: 'Synthetic checklist',
  items: [],
  createdAt: '2026-09-11T12:00:00.000Z',
  updatedAt: '2026-09-11T12:00:00.000Z',
};

const review = {
  stats: { words: 3, sentences: 1, paragraphs: 1 },
  findings: [{
    requirementId: 'requirement-1',
    requirement: 'Explain the result.',
    coverage: 'addressed',
    evidence: 'The result is explained.',
    explanation: 'Your draft covers most of the terms this asks for.',
  }],
  constraintChecks: [{ label: 'At least 3 words', satisfied: true, detail: 'Your draft has 3 words.' }],
};

const aiStatus = {
  selected: 'chrome-local',
  model: 'recommended',
  models: [{ id: 'chrome-on-device', label: 'On-device (Chrome)', recommended: true }],
  providers: [
    {
      providerId: 'chrome-local',
      displayName: 'Chrome built-in',
      cloud: false,
      configured: true,
      status: 'available',
      message: 'Ready.',
      backgroundExecution: false,
      disclosureAccepted: true,
    },
  ],
  autoOpenRelatedTabs: false,
  showOnPagePointer: true,
  allowedConfigurableActions: [],
  lmsAccess: [{ origin: 'https://mylearningspace.wlu.ca/*', granted: true }],
};

const validResults = {
  'ai-status': aiStatus,
  'build-checklist': { checklistId: '123e4567-e89b-12d3-a456-426614174000', items: 2 },
  'get-checklist': checklist,
  'compose-draft': {
    noteId: '123e4567-e89b-12d3-a456-426614174001',
    draft: 'A synthetic draft.',
    label: 'Generated by Motion.',
    unsupported: [],
  },
  'review-draft': { review, summary: 'The draft covers the requirement.' },
  'toggle-requirement': { updated: true },
} as const;

describe('worker result validation', () => {
  for (const [commandType, result] of Object.entries(validResults)) {
    it(`${commandType} accepts a valid result unchanged`, () => {
      expect(parseWorkerResult(commandType as keyof typeof validResults, result)).toEqual(result);
    });
  }

  it('rejects malformed ai-status results', () => {
    expect(parseWorkerResult('ai-status', { ...aiStatus, selected: 'unknown-provider' })).toBeNull();
    expect(parseWorkerResult('ai-status', { ...aiStatus, providers: [{ ...aiStatus.providers[0], status: 4 }] })).toBeNull();
  });

  it('rejects malformed checklist results', () => {
    expect(parseWorkerResult('build-checklist', { checklistId: 4, items: 2 })).toBeNull();
    expect(parseWorkerResult('get-checklist', { ...checklist, title: 4 })).toBeNull();
  });

  it('rejects malformed generated draft results', () => {
    expect(parseWorkerResult('compose-draft', { ...validResults['compose-draft'], draft: 4 })).toBeNull();
    expect(parseWorkerResult('compose-draft', { ...validResults['compose-draft'], reason: 'x'.repeat(1_001) })).toBeNull();
  });

  it('rejects malformed review and toggle results', () => {
    expect(parseWorkerResult('review-draft', { review, summary: 4 })).toBeNull();
    expect(parseWorkerResult('toggle-requirement', { updated: 'yes' })).toBeNull();
  });

  it('returns null for commands without a rendered result schema', () => {
    expect(parseWorkerResult('open-settings', { anything: true })).toBeNull();
  });
});
